spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# minio 文件存储配置信息
minio:
  endpoint: http://192.168.2.110:9090
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: upload


# 阿里云OSS
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: xxx
  accessKeySecret: xxx
  bucketName: test0371
  urlPrefix: https://test0371.oss-cn-beijing.aliyuncs.com


# fastdfs服务器地址
fast_server: http://192.168.2.110:8888/
# fastdfs
#fastdfs:
#  http_server: http://192.168.2.110:8888/      #这个不是fastdfs属性，但是填上之后，在使用FastDFSClientUtil会得到完整的http文件访问路径
#  connect_timeout: 5
#  network_timeout: 30
#  base_path: /mydata/fastdfs/storage      # 存储日志文件的基本路径
#  charset: UTF-8
#  tracker_server:                         # tracker_server 可以配置成数组
#    - 192.168.2.110:22122
#  use_connection_pool: false              # 如果使用连接池默认值为false
#  connection_pool_max_idle_time: 3600     # 空闲时间超过此时间的连接将被关闭，默认值是3600
#  load_fdfs_parameters_from_tracker: false # 如果从跟踪服务器加载FastDFS参数，默认值是false
#  use_storage_id: false
#  storage_ids_filename: storage_ids.conf
##  http:
##    tracker_server_port: 8888             # 端口号必须和nginx里面配置的端口号一致，否则访问不了图片
#  http_anti_steal_token: false            # 如果有防盗链的话，这里true
#  http_secret_key:                        # 密钥-自己设置



